version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    container_name: keycloak_angular
    ports:
      - "9000:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    networks:
      - db-net
volumes:
  mysql_data:
networks:
  db-net:
    driver: bridge